#!/usr/bin/env python3

from sqlalchemy import Table, Column, Integer, String, Date, MetaData, UniqueConstraint

class GoogleAdLibraryDB:
	def __init__(self, engine):
		metadata = MetaData()
		self._define_tables(metadata)
		metadata.create_all(engine)

	def _define_tables(self, metadata):
		self.advertiser_declared_stats_table = Table("advertiser_declared_stats", metadata,
			Column("key", Integer, primary_key = True),
			Column("advertiser_id", String, unique = True),
			Column("advertiser_declared_name", String),
			Column("advertiser_declared_regulatory_id", String),
			Column("advertiser_declared_scope", String),
		)

		self.advertiser_stats_table = Table("advertiser_stats", metadata,
			Column("key", Integer, primary_key = True),
			Column("advertiser_id", String, unique = True),
			Column("advertiser_name", String),
			Column("public_ids_list", String),
			Column("regions", String),
			Column("elections", String),
			Column("total_creatives", Integer),
			Column("spend_usd", Integer),
			Column("spend_eur", Integer),
			Column("spend_inr", Integer),
			Column("spend_bgn", Integer),
			Column("spend_hrk", Integer),
			Column("spend_czk", Integer),
			Column("spend_dkk", Integer),
			Column("spend_huf", Integer),
			Column("spend_pln", Integer),
			Column("spend_ron", Integer),
			Column("spend_sek", Integer),
			Column("spend_gbp", Integer),
		)

		self.advertiser_weekly_spend_table = Table("advertiser_weekly_spend", metadata,
			Column("key", Integer, primary_key = True),
			Column("advertiser_id", String, index = True),
			Column("advertiser_name", String),
			Column("election_cycle", String),
			Column("week_start_date", Date),
			Column("spend_usd", Integer),
			Column("spend_eur", Integer),
			Column("spend_inr", Integer),
			Column("spend_bgn", Integer),
			Column("spend_hrk", Integer),
			Column("spend_czk", Integer),
			Column("spend_dkk", Integer),
			Column("spend_huf", Integer),
			Column("spend_pln", Integer),
			Column("spend_ron", Integer),
			Column("spend_sek", Integer),
			Column("spend_gbp", Integer),
			UniqueConstraint("advertiser_id", "week_start_date"),
		)

		self.campaign_targeting_table = Table("campaign_targeting", metadata,
			Column("key", Integer, primary_key = True),
			Column("campaign_id", String, unique = True),
			Column("age_targeting", String),
			Column("gender_targeting", String),
			Column("geo_targeting_included", String),
			Column("geo_targeting_excluded", String),
			Column("start_date", Date),
			Column("end_date", Date),
			Column("ads_list", String),
			Column("advertiser_id", String, index = True),
			Column("advertiser_name", String),
		)

		self.creative_stats_table = Table("creative_stats", metadata, 
			Column("key", Integer, primary_key = True),
			Column("ad_id", String, index = True),
			Column("ad_url", String),
			Column("ad_type", String, index = True),
			Column("regions", String),
			Column("advertiser_id", String, index = True),
			Column("advertiser_name", String),
			Column("ad_campaigns_list", String),
			Column("date_range_start", Date),
			Column("date_range_end", Date),
			Column("num_of_days", Integer),
			Column("impressions", String),
			Column("spend_usd", String),
			Column("age_targeting", String),
			Column("gender_targeting", String),
			Column("geo_targeting_included", String),
			Column("geo_targeting_excluded", String),
			Column("first_served_timestamp", Date),
			Column("last_served_timestamp", Date),
			Column("spend_range_min_usd", Integer),
			Column("spend_range_max_usd", Integer),
			Column("spend_range_min_eur", Integer),
			Column("spend_range_max_eur", Integer),
			Column("spend_range_min_inr", Integer),
			Column("spend_range_max_inr", Integer),
			Column("spend_range_min_bgn", Integer),
			Column("spend_range_max_bgn", Integer),
			Column("spend_range_min_hrk", Integer),
			Column("spend_range_max_hrk", Integer),
			Column("spend_range_min_czk", Integer),
			Column("spend_range_max_czk", Integer),
			Column("spend_range_min_dkk", Integer),
			Column("spend_range_max_dkk", Integer),
			Column("spend_range_min_huf", Integer),
			Column("spend_range_max_huf", Integer),
			Column("spend_range_min_pln", Integer),
			Column("spend_range_max_pln", Integer),
			Column("spend_range_min_ron", Integer),
			Column("spend_range_max_ron", Integer),
			Column("spend_range_min_sek", Integer),
			Column("spend_range_max_sek", Integer),
			Column("spend_range_min_gbp", Integer),
			Column("spend_range_max_gbp", Integer),
			UniqueConstraint("ad_id", "advertiser_id"),
		)

		self.geo_spend_table = Table("geo_spend", metadata, 
			Column("key", Integer, primary_key = True),
			Column("country", String),
			Column("country_subdivision_primary", String),
			Column("country_subdivision_secondary", String),
			Column("spend_usd", Integer),
			Column("spend_eur", Integer),
			Column("spend_inr", Integer),
			Column("spend_bgn", Integer),
			Column("spend_hrk", Integer),
			Column("spend_czk", Integer),
			Column("spend_dkk", Integer),
			Column("spend_huf", Integer),
			Column("spend_pln", Integer),
			Column("spend_ron", Integer),
			Column("spend_sek", Integer),
			Column("spend_gbp", Integer),
			UniqueConstraint("country", "country_subdivision_primary", "country_subdivision_secondary"),
		)

		self.last_updated_table = Table("last_updated", metadata,
			Column("key", Integer, primary_key = True),
			Column("report_data_updated_date", Date),
		)

		self.top_keywords_history_table = Table("top_keywords_history", metadata,
			Column("key", Integer, primary_key = True),
			Column("election_cycle", String),
			Column("report_date", Date),
			Column("keyword_1", String),
			Column("spend_usd_1", Integer),
			Column("keyword_2", String),
			Column("spend_usd_2", Integer),
			Column("keyword_3", String),
			Column("spend_usd_3", Integer),
			Column("keyword_4", String),
			Column("spend_usd_4", Integer),
			Column("keyword_5", String),
			Column("spend_usd_5", Integer),
			Column("keyword_6", String),
			Column("spend_usd_6", Integer),
			Column("region", String),
			Column("elections", String),
			UniqueConstraint("election_cycle", "report_date"),
		)

